### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by fspafford** [jedmao/tabsanity-vs#12]
I like the idea of this extension, and it seems to work on lines that contain spaces. 

If other text precedes spaces, then it has problems - a backspace only goes back a single space.

I am using Visual Studio 2015.

**Comment by jedmao** [comment]
You are correct that it doesn't work for spaces that occur after text on a line. This is because the whole war between tabs vs. spaces is about indentation, not alignment. The spaces you speak of are considered alignment spaces and should never have tabs in the first place; thus, this plugin has nothing to fix there.

Does that make sense?

Mixing tabs and spaces is more accurately described as mixing "leading" tabs with "leading" spaces. Once you hit text, it is no longer considered indentation.

**Comment by jedmao** [comment]
Closing since there has been no feedback.
